version: '3.9'

services:
  app:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: test_db
      MONGO_COLLECTION: test_collection
      CSV_PATH: data/healthcare_dataset.csv
    volumes:
      - .:/app
    command: ["pytest", "tests/"]

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
